### ISSUE TITLE
[Bug]: Disable Sunrise Does Not Persist Between Loads

### ISSUE THREAD

**Issue by Darkosto** [Mrbysco/ColorfulSkies#2]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

NeoForge 47.1.106

### Minecraft version

1.20.1

### Mod version

1.1.0

### Java version

Java 17.0.6

### Issue Description

When setting the `disablesunrise` option to true via command, it does persist through world loads or client reloads. I have to rerun that command to remove the sunrise graphics every time. Can this be set and saved through loads?

**Comment by Mrbysco** [comment]
Will look into it :)
